//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorrldWebDesign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewID { get; set; }
        public int UserID { get; set; }
        public int CircleID { get; set; }
        public int Rating { get; set; }
        public string Text { get; set; }
    
        public virtual Circle Circle { get; set; }
        public virtual User User { get; set; }
    }
}
